### ISSUE TITLE
Error in newer versions of Flow

### ISSUE THREAD

**Issue by phou87** [fusionjs/fusion-plugin-i18n#178]
I believe this occurs for 0.80 and greater. I'm using 0.82.

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/fusion-plugin-i18n/src/types.js:22:12

Cannot use function type as a type because function type is a value. To get the type of a value use typeof.

     19│ export type I18nDepsType = {
     20│   fetch?: typeof FetchToken.optional,
     21│   hydrationState?: typeof HydrationStateToken.optional,
     22│   loader?: I18nLoaderToken.optional,
     23│ };
     24│
     25│ export type I18nServiceType = {
```

**Comment by KevinGrandon** [comment]
Thank you for filing an issue. We currently have 0.83 installed within this repository, but it could be that we are missing flow fixtures. Could you tell us:

* Which version of fusion-plugin-i18n you are running.
* Which version of fusion-plugin-i18n-react you are running.

**Comment by KevinGrandon** [comment]
Looking again, this appears to be fixed here: https://github.com/fusionjs/fusion-plugin-i18n/blob/master/src/types.js#L22

I think that this is most likely surfaced due to the `-react` version pulling in a version of this repo without the update. We will work on publishing a new version of that library, in the meantime you can fix this with:

`yarn upgrade`
